; Aether LLVM IR - Generated by aether_bootstrap
target triple = "arm64-apple-macosx14.0.0"

; External declarations
declare i32 @putchar(i32)
declare i8* @malloc(i64)
declare void @exit(i32)

define i64 @main() {
entry:
  %t1 = trunc i64 72 to i32
  call i32 @putchar(i32 %t1)
  %t2 = trunc i64 101 to i32
  call i32 @putchar(i32 %t2)
  %t3 = trunc i64 108 to i32
  call i32 @putchar(i32 %t3)
  %t4 = trunc i64 108 to i32
  call i32 @putchar(i32 %t4)
  %t5 = trunc i64 111 to i32
  call i32 @putchar(i32 %t5)
  %t6 = trunc i64 10 to i32
  call i32 @putchar(i32 %t6)
  ret i64 0
}

