// Generated by Aether Native Compiler
.section __TEXT,__text

.global _main
.align 4
_main:
    sub sp, sp, #48
    stp x29, x30, [sp, #32]
    add x29, sp, #32
    stp x19, x20, [sp, #0]
    stp x21, x22, [sp, #16]
.Lmain_body:
    mov x0, #10
    mov x20, x0
    mov x0, #20
    mov x21, x0
    mov x19, x20
    str x19, [sp, #-16]!
    mov x0, x21
    ldr x19, [sp], #16
    add x0, x19, x0
    str x0, [x29, #-8]
    ldr x0, [x29, #-8]
    b .Lmain_return
.Lmain_return:
    ldp x29, x30, [sp, #32]
    ldp x19, x20, [sp, #0]
    ldp x21, x22, [sp, #16]
    add sp, sp, #48
    ret
