; LLVM IR generated by Aether Compiler
target triple = "arm64-apple-macosx14.0.0"

declare i8* @malloc(i64)
declare void @free(i8*)
declare i64 @write(i32, i8*, i64)
declare i64 @read(i32, i8*, i64)
declare i64 @open(i8*, i32, i32)
declare i64 @close(i32)
declare i8* @mmap(i8*, i64, i32, i32, i32, i64)
declare i32 @pthread_create(i64*, i8*, i8* (i8*)*, i8*)
declare i32 @pthread_join(i64, i8**)

define i64 @hash(i64 %key) {
entry:
  %key.addr = alloca i64
  store i64 %key, i64* %key.addr
  %h.addr = alloca i64
  store i64 0, i64* %h.addr
  %i.addr = alloca i64
  store i64 0, i64* %i.addr
  br label %L0
L0:
  %t0 = load i64, i64* %key.addr
  %t1 = load i64, i64* %i.addr
  %t2 = add i64 %t0, %t1
  %t3 = inttoptr i64 %t2 to i8*
  %t4 = load i8, i8* %t3
  %t5 = zext i8 %t4 to i64
  %t6 = icmp ne i64 %t5, 0
  %t7 = zext i1 %t6 to i64
  %t8 = icmp ne i64 %t7, 0
  br i1 %t8, label %L1, label %L2
L1:
  %c.addr = alloca i64
  %t9 = load i64, i64* %key.addr
  %t10 = load i64, i64* %i.addr
  %t11 = add i64 %t9, %t10
  %t12 = inttoptr i64 %t11 to i8*
  %t13 = load i8, i8* %t12
  %t14 = zext i8 %t13 to i64
  store i64 %t14, i64* %c.addr
  %t15 = load i64, i64* %h.addr
  %t16 = mul i64 %t15, 31
  %t17 = load i64, i64* %c.addr
  %t18 = add i64 %t16, %t17
  store i64 %t18, i64* %h.addr
  %t19 = load i64, i64* %i.addr
  %t20 = add i64 %t19, 1
  store i64 %t20, i64* %i.addr
  br label %L0
L2:
  %t21 = load i64, i64* %h.addr
  %t22 = icmp slt i64 %t21, 0
  %t23 = zext i1 %t22 to i64
  %t24 = icmp ne i64 %t23, 0
  br i1 %t24, label %L3, label %L4
L3:
  %t25 = load i64, i64* %h.addr
  %t26 = sub i64 0, %t25
  store i64 %t26, i64* %h.addr
  br label %L5
L4:
  br label %L5
L5:
  %t27 = load i64, i64* %h.addr
  ret i64 0
}

define i64 @test_map() {
entry:
  %cap.addr = alloca i64
  store i64 16, i64* %cap.addr
  %m.addr = alloca i64
  %t0 = call i8* @malloc(i64 24)
  %t1 = ptrtoint i8* %t0 to i64
  store i64 %t1, i64* %m.addr
  %buckets.addr = alloca i64
  %t2 = load i64, i64* %cap.addr
  %t3 = mul i64 %t2, 8
  %t4 = call i8* @malloc(i64 %t3)
  %t5 = ptrtoint i8* %t4 to i64
  store i64 %t5, i64* %buckets.addr
  %i.addr = alloca i64
  store i64 0, i64* %i.addr
  br label %L6
L6:
  %t6 = load i64, i64* %i.addr
  %t7 = load i64, i64* %cap.addr
  %t8 = icmp slt i64 %t6, %t7
  %t9 = zext i1 %t8 to i64
  %t10 = icmp ne i64 %t9, 0
  br i1 %t10, label %L7, label %L8
L7:
  %t11 = load i64, i64* %buckets.addr
  %t12 = load i64, i64* %i.addr
  %t13 = mul i64 %t12, 8
  %t14 = add i64 %t11, %t13
  %t15 = inttoptr i64 %t14 to i64*
  store i64 0, i64* %t15
  %t16 = load i64, i64* %i.addr
  %t17 = add i64 %t16, 1
  store i64 %t17, i64* %i.addr
  br label %L6
L8:
  %t18 = load i64, i64* %m.addr
  %t19 = load i64, i64* %buckets.addr
  %t20 = inttoptr i64 %t18 to i64*
  store i64 %t19, i64* %t20
  %t21 = load i64, i64* %m.addr
  %t22 = add i64 %t21, 8
  %t23 = inttoptr i64 %t22 to i64*
  store i64 0, i64* %t23
  %t24 = load i64, i64* %m.addr
  %t25 = add i64 %t24, 16
  %t26 = load i64, i64* %cap.addr
  %t27 = inttoptr i64 %t25 to i64*
  store i64 %t26, i64* %t27
  %key.addr = alloca i64
  %t28 = call i8* @malloc(i64 4)
  %t29 = ptrtoint i8* %t28 to i64
  store i64 %t29, i64* %key.addr
  %t30 = load i64, i64* %key.addr
  %t31 = inttoptr i64 %t30 to i8*
  %t32 = trunc i64 102 to i8
  store i8 %t32, i8* %t31
  %t33 = load i64, i64* %key.addr
  %t34 = add i64 %t33, 1
  %t35 = inttoptr i64 %t34 to i8*
  %t36 = trunc i64 111 to i8
  store i8 %t36, i8* %t35
  %t37 = load i64, i64* %key.addr
  %t38 = add i64 %t37, 2
  %t39 = inttoptr i64 %t38 to i8*
  %t40 = trunc i64 111 to i8
  store i8 %t40, i8* %t39
  %t41 = load i64, i64* %key.addr
  %t42 = add i64 %t41, 3
  %t43 = inttoptr i64 %t42 to i8*
  %t44 = trunc i64 0 to i8
  store i8 %t44, i8* %t43
  %h.addr = alloca i64
  %t45 = load i64, i64* %key.addr
  %t46 = call i64 @hash(i64 %t45)
  store i64 %t46, i64* %h.addr
  %t47 = load i64, i64* %h.addr
  %t48 = icmp eq i64 %t47, 0
  %t49 = zext i1 %t48 to i64
  %t50 = icmp ne i64 %t49, 0
  br i1 %t50, label %L9, label %L10
L9:
  ret i64 1
  br label %L11
L10:
  br label %L11
L11:
  %idx.addr = alloca i64
  %t51 = load i64, i64* %h.addr
  %t52 = load i64, i64* %cap.addr
  %t53 = srem i64 %t51, %t52
  store i64 %t53, i64* %idx.addr
  %b.addr = alloca i64
  %t54 = load i64, i64* %m.addr
  %t55 = inttoptr i64 %t54 to i64*
  %t56 = load i64, i64* %t55
  store i64 %t56, i64* %b.addr
  %entry.addr = alloca i64
  %t57 = call i8* @malloc(i64 24)
  %t58 = ptrtoint i8* %t57 to i64
  store i64 %t58, i64* %entry.addr
  %t59 = load i64, i64* %entry.addr
  %t60 = load i64, i64* %key.addr
  %t61 = inttoptr i64 %t59 to i64*
  store i64 %t60, i64* %t61
  %t62 = load i64, i64* %entry.addr
  %t63 = add i64 %t62, 8
  %t64 = inttoptr i64 %t63 to i64*
  store i64 42, i64* %t64
  %t65 = load i64, i64* %entry.addr
  %t66 = add i64 %t65, 16
  %t67 = load i64, i64* %b.addr
  %t68 = load i64, i64* %idx.addr
  %t69 = mul i64 %t68, 8
  %t70 = add i64 %t67, %t69
  %t71 = inttoptr i64 %t70 to i64*
  %t72 = load i64, i64* %t71
  %t73 = inttoptr i64 %t66 to i64*
  store i64 %t72, i64* %t73
  %t74 = load i64, i64* %b.addr
  %t75 = load i64, i64* %idx.addr
  %t76 = mul i64 %t75, 8
  %t77 = add i64 %t74, %t76
  %t78 = load i64, i64* %entry.addr
  %t79 = inttoptr i64 %t77 to i64*
  store i64 %t78, i64* %t79
  %e.addr = alloca i64
  %t80 = load i64, i64* %b.addr
  %t81 = load i64, i64* %idx.addr
  %t82 = mul i64 %t81, 8
  %t83 = add i64 %t80, %t82
  %t84 = inttoptr i64 %t83 to i64*
  %t85 = load i64, i64* %t84
  store i64 %t85, i64* %e.addr
  %val.addr = alloca i64
  %t86 = load i64, i64* %e.addr
  %t87 = add i64 %t86, 8
  %t88 = inttoptr i64 %t87 to i64*
  %t89 = load i64, i64* %t88
  store i64 %t89, i64* %val.addr
  %t90 = load i64, i64* %val.addr
  %t91 = icmp ne i64 %t90, 42
  %t92 = zext i1 %t91 to i64
  %t93 = icmp ne i64 %t92, 0
  br i1 %t93, label %L12, label %L13
L12:
  ret i64 2
  br label %L14
L13:
  br label %L14
L14:
  ret i64 0
}

define i64 @main() {
entry:
  %t0 = call i64 @test_map()
  ret i64 0
}

