; LLVM IR generated by Aether Compiler
target triple = "arm64-apple-macosx14.0.0"

declare i8* @malloc(i64)
declare void @free(i8*)
declare i64 @write(i32, i8*, i64)
declare i64 @read(i32, i8*, i64)
declare i64 @open(i8*, i32, i32)
declare i64 @close(i32)
declare i8* @mmap(i8*, i64, i32, i32, i32, i64)
declare i32 @pthread_create(i64*, i8*, i8* (i8*)*, i8*)
declare i32 @pthread_join(i64, i8**)

define i64 @strlen(i64 %s) {
entry:
  %s.addr = alloca i64
  store i64 %s, i64* %s.addr
  %i.addr = alloca i64
  store i64 0, i64* %i.addr
  br label %L0
L0:
  %t0 = load i64, i64* %s.addr
  %t1 = load i64, i64* %i.addr
  %t2 = add i64 %t0, %t1
  %t3 = inttoptr i64 %t2 to i8*
  %t4 = load i8, i8* %t3
  %t5 = zext i8 %t4 to i64
  %t6 = icmp ne i64 %t5, 0
  %t7 = zext i1 %t6 to i64
  %t8 = icmp ne i64 %t7, 0
  br i1 %t8, label %L1, label %L2
L1:
  %t9 = load i64, i64* %i.addr
  %t10 = add i64 %t9, 1
  store i64 %t10, i64* %i.addr
  br label %L0
L2:
  %t11 = load i64, i64* %i.addr
  ret i64 0
}

define i64 @test_str() {
entry:
  %s.addr = alloca i64
  %t0 = call i8* @malloc(i64 16)
  %t1 = ptrtoint i8* %t0 to i64
  store i64 %t1, i64* %s.addr
  %t2 = load i64, i64* %s.addr
  %t3 = inttoptr i64 %t2 to i8*
  %t4 = trunc i64 72 to i8
  store i8 %t4, i8* %t3
  %t5 = load i64, i64* %s.addr
  %t6 = add i64 %t5, 1
  %t7 = inttoptr i64 %t6 to i8*
  %t8 = trunc i64 101 to i8
  store i8 %t8, i8* %t7
  %t9 = load i64, i64* %s.addr
  %t10 = add i64 %t9, 2
  %t11 = inttoptr i64 %t10 to i8*
  %t12 = trunc i64 108 to i8
  store i8 %t12, i8* %t11
  %t13 = load i64, i64* %s.addr
  %t14 = add i64 %t13, 3
  %t15 = inttoptr i64 %t14 to i8*
  %t16 = trunc i64 108 to i8
  store i8 %t16, i8* %t15
  %t17 = load i64, i64* %s.addr
  %t18 = add i64 %t17, 4
  %t19 = inttoptr i64 %t18 to i8*
  %t20 = trunc i64 111 to i8
  store i8 %t20, i8* %t19
  %t21 = load i64, i64* %s.addr
  %t22 = add i64 %t21, 5
  %t23 = inttoptr i64 %t22 to i8*
  %t24 = trunc i64 0 to i8
  store i8 %t24, i8* %t23
  %len.addr = alloca i64
  %t25 = load i64, i64* %s.addr
  %t26 = call i64 @strlen(i64 %t25)
  store i64 %t26, i64* %len.addr
  %t27 = load i64, i64* %len.addr
  %t28 = icmp ne i64 %t27, 5
  %t29 = zext i1 %t28 to i64
  %t30 = icmp ne i64 %t29, 0
  br i1 %t30, label %L3, label %L4
L3:
  ret i64 1
  br label %L5
L4:
  br label %L5
L5:
  %first.addr = alloca i64
  %t31 = load i64, i64* %s.addr
  %t32 = inttoptr i64 %t31 to i8*
  %t33 = load i8, i8* %t32
  %t34 = zext i8 %t33 to i64
  store i64 %t34, i64* %first.addr
  %t35 = load i64, i64* %first.addr
  %t36 = icmp ne i64 %t35, 72
  %t37 = zext i1 %t36 to i64
  %t38 = icmp ne i64 %t37, 0
  br i1 %t38, label %L6, label %L7
L6:
  ret i64 2
  br label %L8
L7:
  br label %L8
L8:
  ret i64 0
}

define i64 @main() {
entry:
  %t0 = call i64 @test_str()
  ret i64 0
}

