; LLVM IR generated by Aether Compiler
target triple = "arm64-apple-macosx14.0.0"

declare i8* @malloc(i64)
declare void @free(i8*)
declare i64 @write(i32, i8*, i64)
declare i64 @read(i32, i8*, i64)
declare i64 @open(i8*, i32, i32)
declare i64 @close(i32)
declare i8* @mmap(i8*, i64, i32, i32, i32, i64)
declare i32 @pthread_create(i64*, i8*, i8* (i8*)*, i8*)
declare i32 @pthread_join(i64, i8**)

define i64 @test_vec() {
entry:
  %v.addr = alloca i64
  %t0 = call i8* @malloc(i64 24)
  %t1 = ptrtoint i8* %t0 to i64
  store i64 %t1, i64* %v.addr
  %data.addr = alloca i64
  %t2 = call i8* @malloc(i64 64)
  %t3 = ptrtoint i8* %t2 to i64
  store i64 %t3, i64* %data.addr
  %t4 = load i64, i64* %v.addr
  %t5 = load i64, i64* %data.addr
  %t6 = inttoptr i64 %t4 to i64*
  store i64 %t5, i64* %t6
  %t7 = load i64, i64* %v.addr
  %t8 = add i64 %t7, 8
  %t9 = inttoptr i64 %t8 to i64*
  store i64 0, i64* %t9
  %t10 = load i64, i64* %v.addr
  %t11 = add i64 %t10, 16
  %t12 = inttoptr i64 %t11 to i64*
  store i64 8, i64* %t12
  %len.addr = alloca i64
  %t13 = load i64, i64* %v.addr
  %t14 = add i64 %t13, 8
  %t15 = inttoptr i64 %t14 to i64*
  %t16 = load i64, i64* %t15
  store i64 %t16, i64* %len.addr
  %d.addr = alloca i64
  %t17 = load i64, i64* %v.addr
  %t18 = inttoptr i64 %t17 to i64*
  %t19 = load i64, i64* %t18
  store i64 %t19, i64* %d.addr
  %t20 = load i64, i64* %d.addr
  %t21 = load i64, i64* %len.addr
  %t22 = mul i64 %t21, 8
  %t23 = add i64 %t20, %t22
  %t24 = inttoptr i64 %t23 to i64*
  store i64 100, i64* %t24
  %t25 = load i64, i64* %v.addr
  %t26 = add i64 %t25, 8
  %t27 = load i64, i64* %len.addr
  %t28 = add i64 %t27, 1
  %t29 = inttoptr i64 %t26 to i64*
  store i64 %t28, i64* %t29
  %t30 = load i64, i64* %v.addr
  %t31 = add i64 %t30, 8
  %t32 = inttoptr i64 %t31 to i64*
  %t33 = load i64, i64* %t32
  store i64 %t33, i64* %len.addr
  %t34 = load i64, i64* %d.addr
  %t35 = load i64, i64* %len.addr
  %t36 = mul i64 %t35, 8
  %t37 = add i64 %t34, %t36
  %t38 = inttoptr i64 %t37 to i64*
  store i64 200, i64* %t38
  %t39 = load i64, i64* %v.addr
  %t40 = add i64 %t39, 8
  %t41 = load i64, i64* %len.addr
  %t42 = add i64 %t41, 1
  %t43 = inttoptr i64 %t40 to i64*
  store i64 %t42, i64* %t43
  %first.addr = alloca i64
  %t44 = load i64, i64* %d.addr
  %t45 = inttoptr i64 %t44 to i64*
  %t46 = load i64, i64* %t45
  store i64 %t46, i64* %first.addr
  %second.addr = alloca i64
  %t47 = load i64, i64* %d.addr
  %t48 = add i64 %t47, 8
  %t49 = inttoptr i64 %t48 to i64*
  %t50 = load i64, i64* %t49
  store i64 %t50, i64* %second.addr
  %t51 = load i64, i64* %first.addr
  %t52 = icmp ne i64 %t51, 100
  %t53 = zext i1 %t52 to i64
  %t54 = icmp ne i64 %t53, 0
  br i1 %t54, label %L0, label %L1
L0:
  ret i64 1
  br label %L2
L1:
  br label %L2
L2:
  %t55 = load i64, i64* %second.addr
  %t56 = icmp ne i64 %t55, 200
  %t57 = zext i1 %t56 to i64
  %t58 = icmp ne i64 %t57, 0
  br i1 %t58, label %L3, label %L4
L3:
  ret i64 2
  br label %L5
L4:
  br label %L5
L5:
  %final_len.addr = alloca i64
  %t59 = load i64, i64* %v.addr
  %t60 = add i64 %t59, 8
  %t61 = inttoptr i64 %t60 to i64*
  %t62 = load i64, i64* %t61
  store i64 %t62, i64* %final_len.addr
  %t63 = load i64, i64* %final_len.addr
  %t64 = icmp ne i64 %t63, 2
  %t65 = zext i1 %t64 to i64
  %t66 = icmp ne i64 %t65, 0
  br i1 %t66, label %L6, label %L7
L6:
  ret i64 3
  br label %L8
L7:
  br label %L8
L8:
  ret i64 0
}

define i64 @main() {
entry:
  %t0 = call i64 @test_vec()
  ret i64 0
}

