; LLVM IR generated by Aether Compiler
target triple = "arm64-apple-macosx14.0.0"

declare i8* @malloc(i64)
declare void @free(i8*)
declare i64 @write(i32, i8*, i64)
declare i64 @read(i32, i8*, i64)
declare i64 @open(i8*, i32, i32)
declare i64 @close(i32)
declare i8* @mmap(i8*, i64, i32, i32, i32, i64)
declare i32 @pthread_create(i64*, i8*, i8* (i8*)*, i8*)
declare i32 @pthread_join(i64, i8**)

define i64 @test_core() {
entry:
  %ptr.addr = alloca i64
  %t0 = call i8* @malloc(i64 64)
  %t1 = ptrtoint i8* %t0 to i64
  store i64 %t1, i64* %ptr.addr
  %t2 = load i64, i64* %ptr.addr
  %t3 = inttoptr i64 %t2 to i64*
  store i64 12345, i64* %t3
  %val.addr = alloca i64
  %t4 = load i64, i64* %ptr.addr
  %t5 = inttoptr i64 %t4 to i64*
  %t6 = load i64, i64* %t5
  store i64 %t6, i64* %val.addr
  %t7 = load i64, i64* %val.addr
  %t8 = icmp ne i64 %t7, 12345
  %t9 = zext i1 %t8 to i64
  %t10 = icmp ne i64 %t9, 0
  br i1 %t10, label %L0, label %L1
L0:
  ret i64 1
  br label %L2
L1:
  br label %L2
L2:
  %t11 = load i64, i64* %ptr.addr
  %t12 = inttoptr i64 %t11 to i8*
  %t13 = trunc i64 42 to i8
  store i8 %t13, i8* %t12
  %byte.addr = alloca i64
  %t14 = load i64, i64* %ptr.addr
  %t15 = inttoptr i64 %t14 to i8*
  %t16 = load i8, i8* %t15
  %t17 = zext i8 %t16 to i64
  store i64 %t17, i64* %byte.addr
  %t18 = load i64, i64* %byte.addr
  %t19 = icmp ne i64 %t18, 42
  %t20 = zext i1 %t19 to i64
  %t21 = icmp ne i64 %t20, 0
  br i1 %t21, label %L3, label %L4
L3:
  ret i64 2
  br label %L5
L4:
  br label %L5
L5:
  %t22 = load i64, i64* %ptr.addr
  %t23 = inttoptr i64 %t22 to i16*
  %t24 = trunc i64 1000 to i16
  store i16 %t24, i16* %t23
  %short.addr = alloca i64
  %t25 = load i64, i64* %ptr.addr
  %t26 = inttoptr i64 %t25 to i16*
  %t27 = load i16, i16* %t26
  %t28 = zext i16 %t27 to i64
  store i64 %t28, i64* %short.addr
  %t29 = load i64, i64* %short.addr
  %t30 = icmp ne i64 %t29, 1000
  %t31 = zext i1 %t30 to i64
  %t32 = icmp ne i64 %t31, 0
  br i1 %t32, label %L6, label %L7
L6:
  ret i64 3
  br label %L8
L7:
  br label %L8
L8:
  %t33 = load i64, i64* %ptr.addr
  %t34 = inttoptr i64 %t33 to i32*
  %t35 = trunc i64 100000 to i32
  store i32 %t35, i32* %t34
  %word.addr = alloca i64
  %t36 = load i64, i64* %ptr.addr
  %t37 = inttoptr i64 %t36 to i32*
  %t38 = load i32, i32* %t37
  %t39 = zext i32 %t38 to i64
  store i64 %t39, i64* %word.addr
  %t40 = load i64, i64* %word.addr
  %t41 = icmp ne i64 %t40, 100000
  %t42 = zext i1 %t41 to i64
  %t43 = icmp ne i64 %t42, 0
  br i1 %t43, label %L9, label %L10
L9:
  ret i64 4
  br label %L11
L10:
  br label %L11
L11:
  ret i64 0
}

define i64 @main() {
entry:
  %result.addr = alloca i64
  %t0 = call i64 @test_core()
  store i64 %t0, i64* %result.addr
  %t1 = load i64, i64* %result.addr
  ret i64 0
}

